<a href="https://colab.research.google.com/github/MarbleCode/Intro_python/blob/main/numpy_python_by_Haru.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 5

In [2]:
array = np.arange(6)
print(array)

[0 1 2 3 4 5]


# 6

In [ ]:
# [[1,2,3],  
#  [4,5,6],
#  [7,8,9]]
#  3x3
# คล้าย เมทริกซ์
# (แถว , คอลัมน์)
#  [[(0,0),(0,1),(0,2)],  
#  [(1,0),(1,1),(1,2)],
#  [(2,0),(2,1),(2,2)]]

In [4]:
array2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array2D[2,2])

9


In [5]:
print(array2D[1,1])

5


# 7

In [6]:
# array = np.ตำแหน่ง([0,1,2,3,4,5,6,7,8])
array = np.array([20,21,22,23,24,25,26,27,28])
print(array[0])
# print(array[2:7])

20


In [7]:
#print(array[start:stop+1:step])
print(array[2:7])

[22 23 24 25 26]


# 8

In [8]:
array = np.array([20,21,22,23,24,25,26,27])
print(array[array>23])

[24 25 26 27]


# 9

In [9]:
array = np.array([2,3,4,5,6])
array+=1
array*2
print(array)

[3 4 5 6 7]


In [10]:
array*2

array([ 6,  8, 10, 12, 14])

In [11]:
2+2

4

# 10


In [14]:
array1=np.arange(5) #[0,1,2,3,4]

In [15]:
array1

array([0, 1, 2, 3, 4])

In [16]:
array2=np.arange(10,20)

In [17]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
array3=array2[1:6]

In [19]:
array3

array([11, 12, 13, 14, 15])

In [20]:
array4=array3-array1

In [21]:
array4

array([11, 11, 11, 11, 11])

In [22]:
print(array4+array2[2:7])

[23 24 25 26 27]


# function 4 type
## 1. รับค่าเท่านั้น
## 2. รับค่าและส่งค่าด้วย
## 3. ส่งค่าเท่านั้น
## 4. ไม่มีรับค่า ไม่มีส่งค่า

In [28]:
def numpy_sum1(a,b):
  sum=a+b
  print(sum)

In [26]:
def numpy_sum2(a,b):
  sum = a+b
  return sum

In [38]:
def numpy_sum3():
  a=100
  b=200
  sum = a+b
  return sum

In [46]:
def numpy_sum4():
  a=100
  b=200
  sum = a+b
  print(sum)

## การเรียกใช้ฟังก์ชัน method

In [47]:
numpy_sum4()

300


In [50]:
sum4=numpy_sum4()

300


In [51]:
sum4

In [31]:
sum = numpy_sum2(100,200)

In [32]:
sum

300

In [30]:
numpy_sum2(100,200)

300

In [33]:
sum1 = numpy_sum1(100,200)

300


In [34]:
sum1

In [29]:
numpy_sum1(100,200)

300


In [40]:
sum3=numpy_sum3()

In [41]:
sum3

300